blog_app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    subtitle = StringField('Subtitle', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

blog_app/main/routes.py
from flask import render_template, request
from blog_app.models import Post

from flask import Blueprint

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page_index = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page_index, per_page=5)
    return render_template('home.html', posts=posts)


@main.route('/about')
def about():
    return render_template('about.html', title='About')

blog_app/posts/routes.py
from flask import render_template, flash, redirect, url_for, request, abort
from blog_app import db
from blog_app.posts.forms import PostForm
from blog_app.models import User, Post
from flask_login import current_user, login_required
from flask import Blueprint

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, subtitle=form.subtitle.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    # validate form and update database
    if form.validate_on_submit():
        post.title = form.title.data
        post.subtitle = form.subtitle.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.subtitle.data = post.subtitle
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])  # only accept post request for this route
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

blog_app/users/routes.py
from flask import render_template, flash, redirect, url_for, request
from blog_app import bcrypt, db
from blog_app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from blog_app.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required
from blog_app.users.utils import send_email, save_image
from flask import Blueprint

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created!', 'success')
        return redirect(url_for('users.login'))
        # flash message: send one time message
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Wrong email or password. Please try again.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    flash('Successfully logout', 'success')
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.image.data:
            image_file = save_image(form.image.data)
            current_user.img_file = image_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account info has been updated.', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    img_file = url_for('static', filename=f'profile_imgs/{current_user.img_file}')
    return render_template('account.html', title='Account', img_file=img_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page_index = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page_index, per_page=5)
    return render_template('user_post.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Expired or invalid token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

blog_app/templates/about.html
{% extends "layout.html" %}
{% block content %}
<h1>About page</h1>
{% endblock content %}

blog_app/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section" >
            <div class="container mt-3">
                  <div class="row">
                    <div class="col-md-3">
                      <img class="rounded-circle account-img" src="{{ img_file }}" alt="profile image">
                    </div>
                    <div class="col">
                        <h2 class="account-heading">{{current_user.username}}</h2>
                        <p class="text-secondary">{{current_user.email}}</p>
                    </div>
                  </div>
            </div>
    </div>

<!--        update profile section-->
     <div class="content-section">
     <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="text-muted border-bottom mb-3">Update Profile Info</legend>

             <div class="form-group pb-2">
                {{ form.username.label(class="form-control-label") }}
                <!-- error hint-->
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-sm") }}
                {% endif %}
            </div>

             <div class="form-group pb-2">
                {{ form.email.label(class="form-control-label") }}
                <!-- error hint-->
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-sm") }}
                {% endif %}
            </div>

            <div class="form-group pt-2 pb-2">
                {{ form.image.label() }}<br>
                {{ form.image(class="form-control-file") }}<br>
                {% if form.image.errors %}
                    {% for error in form.image.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                {% endif %}
            </div>

        </fieldset>

        <div class="form-group pt-2 pb-2">
            {{ form.submit(class="btn btn-outline-primary") }}
        </div>
     </form>
    </div>
{% endblock content %}

blog_app/templates/create_post.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="text-muted border-bottom mb-3">{{legend}}</legend>

                <div class="form-group pb-2">
                    {{ form.title.label(class="form-control-label") }}
                    <!-- error hint-->
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group pb-2">
                    {{ form.subtitle.label(class="form-control-label") }}
                    <!-- error hint-->
                    {% if form.subtitle.errors %}
                        {{ form.subtitle(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.subtitle.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.subtitle(class="form-control form-control-lg") }}
                    {% endif %}
                </div>


                <div class="form-group pb-2">
                    {{ form.content.label(class="form-control-label") }}
                    <!-- error hint-->
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>
            <div class="form-group pt-2 pb-2">
                {{ form.submit(class="btn btn-outline-primary") }}
            </div>
        </form>

</div>



{% endblock content %}

blog_app/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items: %}
        <article class="media content-section">
            <div class="row">
                <div class="col-md-1">
                    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_imgs/'+post.author.img_file) }}" alt="profile image">
                </div>

                <div class="media-body col" style="margin-left: 15px">
                    <div class="article-metadata">
                      <a style="margin-right: 5px" href="{{ url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
                      <small class="text-muted">{{ post.date_posted.strftime("%Y-%m-%d") }}</small>
                    </div>
                    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                    <p class="article-content">{{ post.subtitle }}</p>
                </div>
            </div>
        </article>
 {% endfor %}
        {% for page_index in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_index %}
                {% if posts.page == page_index  %}
                    <a class="mb-2 me-2 btn btn-dark" href="{{ url_for('main.home', page=page_index) }}">{{ page_index }}</a>
                {% else %}
                    <a class="mb-2 me-2 btn btn-outline-dark" href="{{ url_for('main.home', page=page_index) }}">{{ page_index }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
{% endblock content %}

blog_app/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@400;600&display=swap" rel="stylesheet">

    <!--CSS file-->
    <link rel="stylesheet" href="{{url_for('static', filename='main.css')}}">
    {% if title: %}
        <title>Flask Blog - {{title}}</title>
    {% else: %}
        <title>Flask Blog</title>
    {% endif %}

</head>
<body>
       <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Flask Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
              <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href="{{url_for('posts.new_post')}}">New Post</a>
                    <a class="nav-item nav-link" href="{{url_for('users.account')}}">Account</a>
                    <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
                    <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">


            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for category,message in messages: %}
                        <div class="alert alert-{{category}}">{{message}}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}


            {% block content %}
            {% endblock %}



        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>
              You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

blog_app/templates/login.html
{% extends "layout.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="text-muted border-bottom mb-3">LOGIN IN</legend>


                <div class="form-group pb-2">
                    {{ form.email.label(class="form-control-label") }}
                    <!-- error hint-->
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>


                <div class="form-group pb-2">
                    {{ form.password.label(class="form-control-label") }}
                    <!-- error hint-->
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

<!--                remeber me-->
                <div class="form-check text-muted">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>

            </fieldset>


            <div class="form-group pt-2 pb-2">
                {{ form.submit(class="btn btn-outline-primary") }}
                 <small class="text-muted ms-2"><a href="{{ url_for('users.reset_request') }}">Forgot Password?</a></small>
            </div>


        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don’t have an account? <a class="ml-2" href="{{url_for('users.register')}}">Register</a>
        </small>
    </div>
{% endblock content %}

blog_app/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <div class="row">
            <div class="col-md-1">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_imgs/'+post.author.img_file) }}" alt="profile image">
            </div>

            <div class="media-body col" style="margin-left: 15px">
                <div class="article-metadata">
                  <a style="margin-right: 5px" href="{{ url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
                  <small class="text-muted">{{ post.date_posted.strftime("%Y-%m-%d") }}</small>
                </div>
                {% if post.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm my-3" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-3" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                    </div>
                {% endif %}
                <h2 class="article-title">{{ post.title }}</h2>
                <h5 class="text-muted">{{ post.subtitle }}</h5>
                <br>
                <p class="article-content">{{ post.content}}</p>
            </div>
            </div>
    </article>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                  <input type="submit" class="btn btn-danger" value="Delete">
              </form>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

blog_app/templates/register.html
{% extends "layout.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="text-muted border-bottom md-3">JOIN TODAY! </legend>


                <div class="form-group pb-2">
                    {{ form.username.label(class="form-control-label") }}
                    <!-- error hint-->
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>


                <div class="form-group pb-2">
                    {{ form.email.label(class="form-control-label") }}
                    <!-- error hint-->
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>


                <div class="form-group pb-2">
                    {{ form.password.label(class="form-control-label") }}
                    <!-- error hint-->
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>


                <div class="form-group pb-2">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    <!-- error hint-->
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>


            </fieldset>
            <div class="form-group mt-2 pb-3">
                {{ form.submit(class="btn btn-outline-primary") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{{url_for('users.login')}}"> Login</a>
        </small>
    </div>
{% endblock content %}

blog_app/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="text-muted border-bottom mb-3">Reset Password</legend>


                <div class="form-group pb-2">
                    {{ form.email.label(class="form-control-label") }}
                    <!-- error hint-->
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group pt-2 pb-2">
                {{ form.submit(class="btn btn-outline-primary") }}
            </div>
        </form>
    </div>

{% endblock content %}

blog_app/templates/user_post.html
{% extends "layout.html" %}
{% block content %}
<h3 class="mb-3 text-muted">Posts by {{user.username}} ({{ posts.total }})</h3>
    {% for post in posts.items: %}
        <article class="media content-section">
            <div class="row">
                <div class="col-md-1">
                    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_imgs/'+post.author.img_file) }}" alt="profile image">
                </div>

                <div class="media-body col" style="margin-left: 15px">
                    <div class="article-metadata">
                      <a style="margin-right: 5px" href="{{ url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
                      <small class="text-muted">{{ post.date_posted.strftime("%Y-%m-%d") }}</small>
                    </div>
                    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                    <p class="article-content">{{ post.subtitle }}</p>
                </div>
            </div>
        </article>
 {% endfor %}
        {% for page_index in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_index %}
                {% if posts.page == page_index  %}
                    <a class="mb-2 me-2 btn btn-dark" href="{{ url_for('users.user_posts', username=user.username, page=page_index) }}">{{ page_index }}</a>
                {% else %}
                    <a class="mb-2 me-2 btn btn-outline-dark" href="{{ url_for('users.user_posts', username=user.username, page=page_index) }}">{{ page_index }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
{% endblock content %}